project_id = "loitjamnkuvgcpovfkpf"

[functions.create-community]
verify_jwt = true

[functions.check-kyc-status]
verify_jwt = true

[functions.create-payment-order]
verify_jwt = true

[functions.razorpay-webhook]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.start-kyc]
verify_jwt = true

[functions.reset-kyc]
verify_jwt = true
